import = [
"~/.config/alacritty/themes/monokai_pro.toml"
]

[window]
opacity = 1
blur = false
padding = { x = 6, y = 6 }
option_as_alt = "Both"
decorations = "Buttonless"

[font]
# normal = { family = "0xProto Nerd Font", style = "Regular" }
# normal = { family = "GeistMono NF", style = "Regular" }
# normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 18

[cursor]
style = { shape = "Beam", blinking = "Never" }
thickness = 0.2
