import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[window]
decorations = "Buttonless"
option_as_alt = "Both"
padding = { x = 6, y = 6 }
blur = true

[font]
normal = { family = "BerkeleyMono Nerd Font", style = "Regular" }
bold = { family = "BerkeleyMono Nerd Font", style = "Bold" }
offset = { y = 8 }
size = 16

[cursor]
style = { shape = "Beam", blinking = "Never" }
thickness = 0.2
