import = ["~/.config/alacritty/themes/carbon-dark.toml"]

[window]
decorations = "Buttonless"
option_as_alt = "Both"
padding = { x = 6, y = 6 }
blur = true

[font]
normal = { family = "BerkeleyMono Nerd Font", style = "Text" }
bold = { family = "BerkeleyMono Nerd Font", style = "Bold" }
italic = { family = "BerkeleyMono Nerd Font", style = "Text Italic"}
offset = { y = 0, x = 1 }
size = 16

[cursor]
style = { shape = "Beam", blinking = "Never" }
thickness = 0.2
