#!/usr/bin/env bash
THINGS3_APP_STORE_ID=904280696

# install build tools
xcode-select --install

# install homebrew
/usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

BREW_PREFIX="$(brew --prefix)"

brew tap | grep -q 'homebrew/cask' || brew tap homebrew/cask
brew tap | grep -q 'homebrew/cask-versions' || brew tap homebrew/cask-versions
brew tap | grep -q 'homebrew/cask-fonts' || brew tap homebrew/cask-fonts
brew tap | grep -q 'homebrew/cask-services' || brew tap homebrew/services

casks=(
  1password
  alfred
  bitwig-studio
  font-inter
  hammerspoon
  google-chrome
  iina
  jetbrains-toolbox
  kitty
  logseq
  scroll-reverser
  transmission
)

pkgs=(
  asdf
  awscli
  bat
  boxes
  cling
  cmake
  cmatrix
  cowsay
  ctags
  fd
  figlet
  findutils
  fish
  fortune
  fzf
  gawk
  git
  git-delta
  gitui
  glow
  gnu-tar
  gnu-which
  grep
  gzip
  highlight
  htop
  httpie
  jq
  lsd
  luarocks
  magic-wormhole
  make
  mas
  mosh
  neovim
  nnn
  openssh
  pandoc
  postgresql
  prettier
  pv
  rename
  ripgrep
  ruby
  shellcheck
  speedtest-cli
  starship
  stow
  wget
  zoxide
)

# Install all brew packages
for pkg in "${pkgs[@]}"
do
  [ ! -d "$BREW_PREFIX/Cellar/$(basename "$pkg")" ] && brew install "$pkg" || echo "Already installed: $pkg"
done

# Install all brew casks
for cask in "${casks[@]}"
do
	[ ! -d "$BREW_PREFIX/Caskroom/$(basename "$cask")" ] && brew install "$cask" || echo "Already installed: $cask"
done

# install fennel
luarocks install fennel

# symlink dotfiles
stow fish
stow kitty
stow hammerspoon
stow gitui
stow neovim
stow starship
stow surfingkeys

# install things3
mas install "$THINGS3_APP_STORE_ID"

# change default shell for user to fish (will prompt for password)
chsh -s "$(which fish)"

# install neovim packages
nvim --headless +PackerSync +qa

# bootstrap inkd themes
[ ! -d ~/.inkd/ ] && mkdir -p ~/.inkd/ && cp inkd/* ~/.inkd/ || echo "Ink themes already installed"

# bootstrap terminal fonts
cp fonts/*/* ~/Library/Fonts/
