#!/usr/bin/env bash

# install build tools
xcode-select --install

# install homebrew
/usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew tap | grep -q 'homebrew/cask' || brew tap homebrew/cask
brew tap | grep -q 'homebrew/cask-versions' || brew tap homebrew/cask-versions
brew tap | grep -q 'homebrew/cask-fonts' || brew tap homebrew/cask-fonts
brew tap | grep -q 'homebrew/cask-services' || brew tap homebrew/services

casks=(
  1password
  alfred
  bitwig-studio
  font-inter
  hammerspoon
  iina
  jetbrains-toolbox
  kitty
  scroll-reverser
  transmission
)

pkgs=(
  asdf
  awscli
  bat
  boxes
  cling
  cmake
  cmatrix
  cowsay
  ctags
  fd
  figlet
  findutils
  fish
  fortune
  fzf
  gawk
  git
  git-delta
  gitui
  glow
  gnu-tar
  gnu-which
  grep
  gzip
  highlight
  htop
  httpie
  jq
  lsd
  luarocks
  mas
  make
  mosh
  neovim
  nnn
  openssh
  pandoc
  postgresql
  prettier
  pv
  rename
  ripgrep
  ruby
  shellcheck
  speedtest-cli
  starship
  stow
  wget
  zoxide
  zsh
)
# Install all brew packages
for pkg in "${pkgs[@]}"
do
	[ ! -d /usr/local/Cellar/$(basename $pkg) ] && brew install $pkg || echo "Already installed: $pkg"
done

# Install all brew casks
for cask in "${casks[@]}"
do
	[ ! -d /usr/local/Caskroom/$(basename $cask) ] && brew install $cask || echo "Already installed: $cask"
done

# install fennel
luarocks install fennel

# symlink dotfiles
stow kitty
stow hammerspoon
stow fish
stow gitui
stow neovim
stow starship
stow surfingkeys
stow inkd

things3_app_store_id=904280696

mas install "$things3_app_store_id"
