#!/usr/bin/env bash

THINGS3_APP_STORE_ID=904280696

# install build tools
[ ! -d "$(xcode-select -p)" ] && xcode-select --install

# install homebrew
[ -z "$(which brew)" ] && /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

BREW_PREFIX="$(brew --prefix)"

brew tap | grep -q 'homebrew/cask' || brew tap homebrew/cask
brew tap | grep -q 'homebrew/cask-versions' || brew tap homebrew/cask-versions
brew tap | grep -q 'homebrew/cask-fonts' || brew tap homebrew/cask-fonts
brew tap | grep -q 'homebrew/cask-services' || brew tap homebrew/services

# TODO: 
# macos ships with an insanely old version of bash.
# maybe we should install that first before continuing on?

casks=(
  1password
  alfred
  bitwig-studio
  font-inter
  hammerspoon
  google-chrome
  google-drive
  iina
  jetbrains-toolbox
  kitty
  logseq
  scroll-reverser
  transmission
)

pkgs=(
  asdf
  awscli
  bat
  boxes
  cling
  cmake
  cmatrix
  cowsay
  ctags
  fd
  figlet
  findutils
  fish
  fortune
  fzf
  gawk
  git
  git-delta
  gitui
  glow
  gnu-tar
  gnu-which
  grep
  gzip
  highlight
  htop
  httpie
  jq
  lsd
  luarocks
  magic-wormhole
  make
  mas
  mosh
  neovim
  nnn
  openssh
  pandoc
  postgresql
  prettier
  pv
  rename
  ripgrep
  ruby
  shellcheck
  speedtest-cli
  starship
  stow
  wget
  zoxide
)

# Install all brew packages
for pkg in "${pkgs[@]}"
do
  [ ! -d "$BREW_PREFIX/Cellar/$(basename "$pkg")" ] && brew install "$pkg" || echo "Already installed: $pkg"
done

# Install all brew casks
for cask in "${casks[@]}"
do
	[ ! -d "$BREW_PREFIX/Caskroom/$(basename "$cask")" ] && brew install "$cask" || echo "Already installed: $cask"
done

# install fennel
[ -z "$(which fennel)" ] && luarocks install fennel

# symlink dotfiles
stow fish
stow kitty
stow hammerspoon
stow gitui
stow neovim
stow starship
stow surfingkeys

# install things3
mas install "$THINGS3_APP_STORE_ID"

# change default shell for user to fish (will prompt for password)
echo "$SHELL" | grep -q 'fish' || chsh -s "$(which fish)"

# install fisher
[ -z "$(fish -c 'fisher -v')" ] && fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

# bootstrap inkd themes
[ ! -d ~/.inkd/ ] && mkdir -p ~/.inkd/ && cp -n inkd/* ~/.inkd/ || echo "Ink themes already installed"

# install neovim packages
INKD_DIR="$HOME/.inkd/" nvim --headless +PackerCompile +PackerSync +qa

# bootstrap terminal fonts
cp -n fonts/*/* ~/Library/Fonts/

# install some environments
asdf_plugins="$(asdf plugin list)"
ruby_installed="$(echo "$asdf_plugins" | grep 'ruby')"
python_installed="$(echo "$asdf_plugins" | grep 'python')"
have_ruby_version="$(asdf list ruby | grep '3.0.2')"
have_python_version="$(asdf list python | grep '3.10.5')"

[ -z "$ruby_installed" ] && asdf plugin add ruby
[ -z "$python_installed" ] && asdf plugin add python
[ -z "$have_ruby_version" ] && asdf install ruby 3.0.2
[ -z "$have_python_version" ] && asdf install python 3.10.5

# set up our global/shell versions of interpreters
asdf global ruby 3.0.2
asdf global python 3.10.5

[ -z "$(asdf which bundler)" ] && asdf exec gem install bundler

brew update
brew upgrade
brew cleanup
