add_newline = true
command_timeout = 1000

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"

[line_break]
disabled = false

[ruby]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[aws]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true
