add_newline = true
command_timeout = 1000

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold yellow)"

[line_break]
disabled = false

[git_branch]
symbol = "󰘬 "
style = "purple"

[ruby]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[aws]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true
