# Monokai Pro
[colors]

[colors.primary]
background = '#2c2525'
foreground = '#fff1f3'

[colors.cursor]
text = '#000000'
cursor = '#ffffff'

[colors.normal]
black = '#2c2525'
red = '#fd6883'
green = '#adda78'
yellow = '#f9cc6c'
blue = '#f38d70'
magenta = '#a8a9eb'
cyan = '#85dacc'
white = '#fff1f3'

# Bright colors
[colors.bright]
black = '#72696a'
red = '#fd6883'
green = '#adda78'
yellow = '#f9cc6c'
blue = '#f38d70'
magenta = '#a8a9eb'
cyan = '#85dacc'
white = '#fff1f3'

# # Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
