# Fuzzel Configuration

font = BerkeleyMono Nerd Font:size=8
dpi-aware = yes
prompt = ''
lines = 25
width = 40

[colors]
background = '282a36ff'
text = 'f8f8f2ff'
border = 'bd93f9ff'
selection = '44475aff'
selection-match = '8be9fdff'
