return {
  "onsails/lspkind.nvim",
  event = "VeryLazy",
  config = function()
    require("lspkind").init({
      symbol_map = {
        Array = "[]",
        Boolean = "",
        Calendar = "",
        Class = "󰠱",
        Codeium = "",
        Comment = "",
        Color = "󰏘",
        Constant = "󰏿",
        Constructor = "",
        Copilot = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "󰜢",
        File = "󰈚",
        Folder = "󰉋",
        Function = "󰆧",
        Interface = "",
        Keyword = "󰌋",
        KeywordFunction = "󰌋",
        KeywordOperator = "󰌋",
        KeywordConditional = "",
        KeywordImport = "",
        KeywordRepeat = "󰌉",
        Label = "",
        MarkupHeading1 = "󰉫",
        MarkupHeading2 = "󰉬",
        MarkupHeading3 = "󰉭",
        MarkupHeading4 = "󰉮",
        MarkupHeading5 = "󰉯",
        MarkupHeading6 = "󰉰",
        Method = "󰆧",
        Module = "",
        Namespace = "󰌗",
        Null = "󰟢",
        Number = "",
        Object = "󰅩",
        Operator = "󰆕",
        Package = "",
        Property = "󰜢",
        Reference = "󰈇",
        Snippet = "",
        Spell = "",
        String = "󰉿",
        StringRegexp = "󰑑",
        StringSpecialSymbol = "󰙴",
        Struct = "󰙅",
        Supermaven = "",
        TabNine = "",
        Table = "",
        Tag = "",
        Text = "󰉿",
        TypeParameter = "󰊄",
        Unit = "󰑭",
        Value = "󰎠",
        Variable = "󰀫",
        VariableMember = "󰀫",
        Watch = "󰥔",
      },
    })
  end,
}
