return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  lazy = false,
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "clojure",
      "cmake",
      "cpp",
      "css",
      "c_sharp",
      "dockerfile",
      "eex",
      "elixir",
      "erlang",
      "fennel",
      "fish",
      "fsharp",
      "go",
      "gomod",
      "haskell",
      "heex",
      "html",
      "java",
      "javascript",
      "json",
      "julia",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "nix",
      "nu",
      "php",
      "python",
      "ruby",
      "rust",
      "scss",
      "sql",
      "surface",
      "svelte",
      "templ",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "zig",
    },
    sync_install = false,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
    indent = { enable = true, disable = { "ruby" } },
  },
}
