#!/usr/bin/env sh
# Fuzz search every file on the filesystem

IFS=$'\n'
out=($(fd -H -a --type f . / | fzf --exit-0 --expect=ctrl-o,ctrl-x \
  --preview-window=up:80% \
  --preview '[[ $(file --mime {}) =~ binary ]] &&
      echo {} is a binary file ||
      preview.sh {} 2> /dev/null | head -2000'))

key=$(head -1 <<< "$out")
file=$(head -2 <<< "$out" | tail -1)

if [ -n "$file" ]; then
  if [ "$key" = ctrl-o ]; then
    open "$file"
  elif [ "$key" = ctrl-x ]; then
    rm -i "$file"
  else
    $EDITOR "$file"
  fi
fi
