#!/bin/bash
ff() {
  local out
  IFS=$'\n'
  out=($(fzf --query="$1" --exit-0  --preview-window=up:75% --preview '[[ $(file --mime {}) =~ binary ]] &&
                  echo {} is a binary file ||
                  (highlight -O ansi -l {} ||
                  pygmentize -g {} ||
                  cat {}) 2> /dev/null | head -2000'))
  # file=$(ghead -2 <<< "$out" | gtail -1)
  if [ -n "$out" ]; then
      nvim "$out"
  fi
}

ff
