#!/usr/bin/env sh

IFS=$'\n'
out=($(rg ${1:-.} --files --no-ignore --hidden --follow \
    -g "!.git/*" \
    -g "!*.pyc" \
    -g "!node-modules/*" \
    -g "!tags" \
    -g "!TAGS" \
    2> /dev/null \
    | fzf +m --exit-0 --expect=ctrl-o,ctrl-x,ctrl-v --preview-window=up:80% \
    --preview '[[ $(file --mime {}) =~ binary ]] &&
        echo {} is a binary file ||
        preview {} 2> /dev/null | head -2000'))

key=$(head -1 <<< "$out")
file=$(head -2 <<< "$out" | tail -1)

if [ -n "$file" ]; then
    if [ "$key" = ctrl-o ]; then
        open "$file"
    elif [ "$key" = ctrl-x ]; then
        rm -i "$file"
    elif [ "$key" = ctrl-v ]; then
        code "$file"
    else
        $EDITOR "$file"
    fi
fi
