#!/bin/bash

IFS=$'\n'
out=($(gsed '1d' ~/.cache/neomru/file |
        fzf --query="$1" --exit-0  --expect=ctrl-o,ctrl-x,ctrl-v --preview-window=right:50% --preview '[[ $(file --mime {}) =~ binary ]] &&
                  echo {} is a binary file ||
                  (highlight -O ansi -l {} ||
                  pygmentize -g {} ||
                  cat {}) 2> /dev/null | head -2000'))
key=$(head -1 <<< "$out")
file=$(head -2 <<< "$out" | tail -1)
if [ -n "$file" ]; then
    if [ "$key" = ctrl-o ]; then
        open "$file"
    elif [ "$key" = ctrl-x ]; then
        rm -i "$file"
    elif [ "$key" = ctrl-v ]; then
        code "$file"
    else
        $EDITOR "$file"
    fi
fi
unset out
unset file
unset key
unset IFS
