#!/usr/bin/env bash
 
# Usage: map-message [stage|prod] [messageapi_id]
#    ex: map-message stage 5ad5e88af227ef6d34e347c7
 
UUID=$(uuidgen | tr '[:upper:]' '[:lower:]')
ENVIRONMENT=$1
 
curl -XPOST -H 'Content-Type: application/json' \
  "http://messagemap.aweber${ENVIRONMENT}.com/" \
  -d "{\"messageapi_id\":\"$2\", \"id\":\"${UUID}\"}"