#!/bin/bash

local out dir key
IFS=$'\n' out="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort --expect=ctrl-o,ctrl-x,ctrl-v,ctrl-e +m)"
key=$(head -1 <<< "$out")
dir=$(head -2 <<< "$out" | tail -1)
if [ -d "$dir" ]; then
    if [ "$key" = ctrl-o ]; then
        open "$dir"
    elif [ "$key" = ctrl-v ]; then
        cd "$dir" && code "$dir"
    elif [ "$key" = ctrl-e ]; then
        cd "$dir" && $EDITOR "$dir"
    elif [ "$key" = ctrl-x ]; then
        rm -ir "$dir"
    else
        cd "$dir"
    fi
fi
unset out
unset key
unset dir
