#!/usr/bin/env python
import argparse
import os
import subprocess
import sys

import chevron
import yaml

DOTS_DIR = os.path.expanduser("~") + "/git/.dotfiles/"
THEME_DIR = DOTS_DIR + "/static/themes/"
# TODO: add xcolors/xresources
# TODO: add rofi
# TODO: add awesome
# TODO: add vifm
TEMPLATE_OUTPUT_MAP = {
    "vim.mustache": "neovim/.config/nvim/colorscheme.vim",
    "env.mustache": "zsh/.zsh/zshcolors",
    "tmux.mustache": "tmux/.tmux-colors.conf",
    "prezto.mustache": "zsh/.zprezto-colors.zsh",
    # "lightline.mustache": "neovim/.local/share/nvim/plugged/lightline.vim/autoload/lightline/colorscheme/termina.vim"
}


def render_file(template_path, output_path, data):
    with open(template_path, "r") as temp:
        rendered = chevron.render(**{"template": temp, "data": data})
    with open(output_path, "w") as output:
        output.write(rendered)
        output.close()


def render_to_stdout(template_path, output_path, data):
    with open(template_path, "r") as temp:
        rendered = chevron.render(**{"template": temp, "data": data})
        print(rendered)


def change_iterm_profile(theme):
    command = f"iterm-profile {theme}"
    call_with_shell(command)


def reload_tmux():
    command = "tmux source-file ~/.tmux.conf"
    call_with_shell(command)


def load_alfred_theme(theme):
    command = ["osascript", "-e", f'tell application "Alfred 3" to set theme "{theme}"']
    subprocess.Popen(command)


def call_with_shell(command):
    subprocess.call([os.getenv("SHELL"), "-i", "-c", command])


def load_theme_yaml(theme):
    with open(f"{THEME_DIR + theme}.yaml", "r") as f:
        try:
            return yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"Theme failed to load: {THEME_DIR + theme}")
            print(e)


def main():
    themes = [theme.split(".")[0] for theme in os.listdir(THEME_DIR)]
    parser = argparse.ArgumentParser(description="Switch to a theme")
    g = parser.add_mutually_exclusive_group()
    g.add_argument("--list-themes", action="store_true")
    g.add_argument(
        "theme", type=str, nargs="?", metavar="THEME", choices=themes, help="theme name"
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.list_themes:
        for theme in themes:
            print(theme)
        return

    theme_data = load_theme_yaml(args.theme)
    theme = args.theme
    if args.dry_run:
        for template, output in TEMPLATE_OUTPUT_MAP.items():
            template_file = DOTS_DIR + "static" + "/" + template
            output_file = DOTS_DIR + output
            print("****************************************")
            print(f"*****************  {output_file}  **************")
            render_to_stdout(template_file, output_file, theme_data)
        print(f'iTerm profile changed to "{theme}"')
    else:
        for template, output in TEMPLATE_OUTPUT_MAP.items():
            template_file = DOTS_DIR + "static" + "/" + template
            output_file = DOTS_DIR + output
            render_file(template_file, output_file, theme_data)
        if sys.platform == "darwin":
            change_iterm_profile(theme)
            load_alfred_theme(theme)
        reload_tmux()


if __name__ == "__main__":
    main()
