#!/usr/bin/env python
import argparse
import os
import subprocess
import sys

import chevron
import yaml

ENABLED_APPS = ["neovim", "zsh", "tmux", "rofi", "xorg", "statusline"]


class Renderer:
    apps = {
        "neovim": {
            "os_types": ["linux", "darwin"],
            "template": "vim.mustache",
            "output_file": "colorscheme.vim",
            "output_path": "neovim/.config/nvim/",
        },
        "statusline": {
            "os_types": ["linux", "darwin"],
            "template": "statusline.mustache",
            "output_file": "statusline.vim",
            "output_path": "neovim/.config/nvim/",
        },
        "zsh": {
            "os_types": ["linux", "darwin"],
            "template": "env.mustache",
            "output_file": "zshcolors",
            "output_path": "zsh/.zsh/",
        },
        "tmux": {
            "os_types": ["linux", "darwin"],
            "template": "tmux.mustache",
            "output_file": ".tmux-colors.conf",
            "output_path": "tmux/",
        },
        "lightline": {
            "os_types": ["linux", "darwin"],
            "template": "lightline.mustache",
            "output_file": "termina.vim",
            "output_path": "neovim/.local/share/nvim/plugged/lightline.vim/autoload/lightline/colorscheme/",
        },
        "xorg": {
            "os_types": ["linux"],
            "template": "xcolors.mustache",
            "output_file": ".xresources",
            "output_path": "xorg/",
        },
        "rofi": {
            "os_types": ["linux"],
            "template": "rofi.mustache",
            "output_file": "theme.rasi",
            "output_path": "rofi/.config/rofi/themes/",
        },
        "vifm": {
            "os_types": ["darwin", "linux"],
            "template": "vifm.mustache",
            "output_file": "vifm-colors",
            "output_path": "vifm/.config/vifm/",
        },
    }

    def __init__(self):
        self.dots_dir = os.path.expanduser("~") + "/git/.dotfiles/"
        self.theme_dir = self.dots_dir + "/templates/themes/"
        self.themes = [theme.split(".")[0] for theme in os.listdir(self.theme_dir)]

    def print_themes(self):
        for theme in self.themes:
            print(theme)

    def render_themed_files(self, theme, dry_run=True):
        theme_data = self.load_theme_data(theme)
        for app, data in self.apps.items():
            template = self.dots_dir + "templates" + "/" + data["template"]
            output = self.dots_dir + data["output_path"] + data["output_file"]
            if app in ENABLED_APPS:
                if dry_run:
                    print(
                        f"*********************** Rendering to '{output}'  ***************************"
                    )
                    self.render_to_stdout(template, output, theme_data)
                else:
                    if sys.platform in data['os_types']:
                        self.render_file(template, output, theme_data)

    @staticmethod
    def render_file(template_path, output_path, data):
        with open(template_path, "r") as temp:
            rendered = chevron.render(**{"template": temp, "data": data})
        with open(output_path, "w") as output:
            output.write(rendered)
            output.close()

    @staticmethod
    def render_to_stdout(template_path, output_path, data):
        with open(template_path, "r") as temp:
            rendered = chevron.render(**{"template": temp, "data": data})
            print(rendered)

    def load_theme_data(self, theme):
        with open(f"{self.theme_dir + theme}.yaml", "r") as f:
            try:
                return yaml.safe_load(f)
            except yaml.YAMLError as e:
                print(f"Theme failed to load: {self.theme_dir + theme}")
                print(e)


class Shell:
    def __init__(self):
        self.platform = sys.platform

    def load_theme(self, theme):
        if self.platform == "darwin":
            self.change_iterm_profile(theme)
            self.load_alfred_theme(theme)
        if self.platform == "linux":
            self.reload_xresources()
        self.reload_tmux()

    def change_iterm_profile(self, theme):
        command = f"iterm-profile {theme}"
        self.call_with_shell(command)

    def reload_tmux(self):
        command = "tmux source-file ~/.tmux.conf"
        self.call_with_shell(command)

    def load_alfred_theme(self, theme):
        command = [
            "osascript",
            "-e",
            f'tell application "Alfred 3" to set theme "{theme}"',
        ]
        subprocess.Popen(command)

    def call_with_shell(self, command):
        subprocess.call([os.getenv("SHELL"), "-i", "-c", command])

    def restart_awesome():
        raise NotImplementedError()

    def reload_xresources():
        call_with_shell("xrdb merge " + os.expanduser("~") + "/.xresources")


def parse_arguments(themes):
    parser = argparse.ArgumentParser(description="Switch to a theme")
    g = parser.add_mutually_exclusive_group()
    g.add_argument("--list-themes", action="store_true")
    g.add_argument(
        "theme", type=str, nargs="?", metavar="THEME", choices=themes, help="theme name"
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def main():
    renderer = Renderer()
    shell = Shell()
    args = parse_arguments(renderer.themes)

    if args.list_themes:
        renderer.print_themes()
        return

    renderer.render_themed_files(args.theme, dry_run=args.dry_run)
    if not args.dry_run:
        shell.load_theme(args.theme)


if __name__ == "__main__":
    main()
