#!/usr/bin/env sh

data=$(bmon -p 'wl*' -o format:quitafter=2)

first_rx=$(echo "$data" | sed -n 1p | awk '{print $2}')
second_rx=$(echo "$data" | sed -n 2p | awk '{print $2}')

first_tx=$(echo "$data" | sed -n 1p | awk '{print $4}')
second_tx=$(echo "$data" | sed -n 2p | awk '{print $4}')

rx_diff=$(echo $(($second_rx - $first_rx)) | awk '{ split( "KB MB GB" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } print int($1) v[s] }')
tx_diff=$(echo $(($second_tx - $first_tx)) | awk '{ split( "KB MB GB" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } print int($1) v[s] }')

echo "$rx_diff:$tx_diff"
