#!/usr/bin/env sh
latlon=$(http GET http://ip-api.com/json/$(http GET ifconfig.me) | jq -r '[.lat, .lon] | join(",")')

if [ -z "$latlon" ]; then
    # Fall back to Philadelphia if latlon is unavailable
    latlon="39.93,-75.18"
fi

weather=$(http GET "https://api.darksky.net/forecast/${DARKSKY_API_KEY}/${latlon}?exclude=minutely,daily")

if [ ! -z "$weather" ]; then
    today_icon=$(echo "$weather" | jq -r '.currently.icon')
    today_temp=$(echo "$weather" | jq -r '.currently.temperature')
    today_summary=$(echo "$weather" | jq -r '.hourly.summary')
    icon0=$(echo "$weather" | jq -r '.daily.data.[0].icon')
    summary0=$(echo "$weather" | jq -r '.daily.data.[0].summary')
    templow0=$(echo "$weather" | jq -r '.daily.data.[0].temperatureLow')
    temphigh0=$(echo "$weather" | jq -r '.daily.data.[0].temperatureHigh')
    icon1=$(echo "$weather" | jq -r '.daily.data.[1].icon')
    summary1=$(echo "$weather" | jq -r '.daily.data.[1].summary')
    templow1=$(echo "$weather" | jq -r '.daily.data.[1].temperatureLow')
    temphigh1=$(echo "$weather" | jq -r '.daily.data.[1].temperatureHigh')
    icon2=$(echo "$weather" | jq -r '.daily.data.[2].icon')
    summary2=$(echo "$weather" | jq -r '.daily.data.[2].summary')
    templow2=$(echo "$weather" | jq -r '.daily.data.[2].temperatureLow')
    temphigh2=$(echo "$weather" | jq -r '.daily.data.[2].temperatureHigh')
    icon3=$(echo "$weather" | jq -r '.daily.data.[3].icon')
    summary3=$(echo "$weather" | jq -r '.daily.data.[3].summary')
    templow3=$(echo "$weather" | jq -r '.daily.data.[3].temperatureLow')
    temphigh3=$(echo "$weather" | jq -r '.daily.data.[3].temperatureHigh')
    icon4=$(echo "$weather" | jq -r '.daily.data.[4].icon')
    summary4=$(echo "$weather" | jq -r '.daily.data.[4].summary')
    templow4=$(echo "$weather" | jq -r '.daily.data.[4].temperatureLow')
    temphigh4=$(echo "$weather" | jq -r '.daily.data.[4].temperatureHigh')
    icon5=$(echo "$weather" | jq -r '.daily.data.[5].icon')
    summary5=$(echo "$weather" | jq -r '.daily.data.[5].summary')
    templow5=$(echo "$weather" | jq -r '.daily.data.[5].temperatureLow')
    temphigh5=$(echo "$weather" | jq -r '.daily.data.[5].temperatureHigh')
    icon6=$(echo "$weather" | jq -r '.daily.data.[6].icon')
    summary6=$(echo "$weather" | jq -r '.daily.data.[6].summary')
    templow6=$(echo "$weather" | jq -r '.daily.data.[6].temperatureLow')
    temphigh6=$(echo "$weather" | jq -r '.daily.data.[6].temperatureHigh')
    icon7=$(echo "$weather" | jq -r '.daily.data.[7].icon')
    summary7=$(echo "$weather" | jq -r '.daily.data.[7].summary')
    templow7=$(echo "$weather" | jq -r '.daily.data.[7].temperatureLow')
    temphigh7=$(echo "$weather" | jq -r '.daily.data.[7].temperatureHigh')
else
    echo "..."
    exit 1
fi

today="$today_icon:$today_temp:$today_summary"
day0="$icon0:$summary0:$templow0:$temphigh0"
day1="$icon1:$summary1:$templow1:$temphigh1"
day2="$icon2:$summary2:$templow2:$temphigh2"
day3="$icon3:$summary3:$templow3:$temphigh3"
day4="$icon4:$summary4:$templow4:$temphigh4"
day5="$icon5:$summary5:$templow5:$temphigh5"
day6="$icon6:$summary6:$templow6:$temphigh6"
day7="$icon7:$summary7:$templow7:$temphigh7"

echo "$today:$day0:$day1:$day2:$day3:$day4:$day5:$day6:$day7"
