# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/borders/bin/borders',
]

[mode.main.binding]
cmd-ctrl-alt-h = 'focus left'
cmd-ctrl-alt-j = 'focus down'
cmd-ctrl-alt-k = 'focus up'
cmd-ctrl-alt-l = 'focus right'

cmd-ctrl-alt-shift-h = 'move left'
cmd-ctrl-alt-shift-j = 'move down'
cmd-ctrl-alt-shift-k = 'move up'
cmd-ctrl-alt-shift-l = 'move right'

ctrl-cmd-alt-f = 'fullscreen'
cmd-ctrl-alt-up = 'join-with up'
cmd-ctrl-alt-down = 'join-with down'
cmd-ctrl-alt-left = 'join-with left'
cmd-ctrl-alt-right = 'join-with right'

cmd-ctrl-alt-s = 'layout v_accordion'               # 'layout stacking' in i3
cmd-ctrl-alt-w = 'layout h_accordion'               # 'layout tabbed' in i3
cmd-ctrl-alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-ctrl-alt-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

cmd-ctrl-alt-1 = 'workspace 1'
cmd-ctrl-alt-2 = 'workspace 2'
cmd-ctrl-alt-3 = 'workspace 3'
cmd-ctrl-alt-4 = 'workspace 4'
cmd-ctrl-alt-5 = 'workspace 5'
cmd-ctrl-alt-6 = 'workspace 6'
cmd-ctrl-alt-7 = 'workspace 7'
cmd-ctrl-alt-8 = 'workspace 8'
cmd-ctrl-alt-9 = 'workspace 9'
cmd-ctrl-alt-0 = 'workspace 10'

cmd-ctrl-alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-ctrl-alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-ctrl-alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-ctrl-alt-shift-4 = 'move-node-to-workspace 4'
cmd-ctrl-alt-shift-5 = 'move-node-to-workspace 5'
cmd-ctrl-alt-shift-6 = 'move-node-to-workspace 6'
cmd-ctrl-alt-shift-7 = 'move-node-to-workspace 7'
cmd-ctrl-alt-shift-8 = 'move-node-to-workspace 8'
cmd-ctrl-alt-shift-9 = 'move-node-to-workspace 9'
cmd-ctrl-alt-shift-0 = 'move-node-to-workspace 10'

cmd-ctrl-alt-shift-c = 'reload-config'

cmd-ctrl-alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[workspace-to-monitor-force-assignment]
1 = 3
2 = 2
3 = 1
