set -g status-position bottom
set -g status-justify "centre"
set -g status-style "bg=#282C34"
set -g window-style "bg=#2C323D"
set -g mode-style "bg=#505868 fg=#46D9FF"

set -g status-left "#[fg=#505868]#[fg=colour03 bg=#505868] #[fg=colour05 bg=#393f4a] #S#[fg=#393f4a bg=#282C34] "
set -g status-left-length 100

set -g status-right "#[fg=#393f4a]#[fg=#ecbe7b bg=#393f4a]%I:%M %p#[fg=#393f4a bg=#282C34] #[fg=#393f4a]#[fg=#98be65 bg=#393f4a]%b %d#[fg=#393f4a bg=#282C34] #{battery_status_fg}#{battery_percentage} "
set -g status-right-style "bold"
set -g status-right-length 100

# set -g window-status-format "#{?#{==:#{window_name},zsh},#{b:pane_current_path},#W}#{?window_zoomed_flag,.Z,} "
set -g window-status-format "#[fg=#393f4a bg=#282C34]#[fg=#6f7683 bg=#393f4a]#{b:pane_current_path}#[fg=#393f4a bg=#282C34] "
# set -g window-status-current-format "#{?#{==:#{window_name},zsh},#{b:pane_current_path},#W}#{?window_zoomed_flag,.Z,} "
set -g window-status-current-format "#[fg=#393f4a bg=#282C34]#[fg=#51afef bg=#393f4a]#{?#{==:#{window_name},zsh},#{b:pane_current_path},#W}#{?window_zoomed_flag,.Z,}#[fg=#393f4a bg=#282C34] "
set -g window-status-separator ""

set -g pane-active-border-style "fg=#282C34 bg=#282C34"
set -g pane-border-style "fg=#282C34 bg=#282C34"

set -g window-active-style "bg=#282C34"
set -g window-status-activity-style "fg=#ecbe7b"
