# Spacemux
unbind C-b
set-option -g prefix M-Space
bind Space send-prefix

# shell
set -g default-shell /usr/local/bin/zsh
set -g default-command "main > /dev/null 2>&1; reattach-to-user-namespace -l ${SHELL}"

# start with window 1 (instead of 0)
set -g base-index 1

# start with pane 1
set -g pane-base-index 1

# source config file
bind r source-file ~/.tmux.conf

# history
set -g history-limit 16384

# allow terminal scrolling
set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'

# vim style copy paste mode
unbind [
bind C-u copy-mode
unbind p
bind p paste-buffer
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -Tcopy-mode-vi Escape send -X cancel
bind-key -Tcopy-mode-vi V send -X rectangle-toggle

# pleb mode
set -g mouse on

# splitting
unbind %
bind v split-window -h -c '#{pane_current_path}'
unbind '"'
bind s split-window -v -c '#{pane_current_path}'

# colon is prompt
bind : command-prompt

# resizing
setw -g aggressive-resize off

# some key-binding changes
bind q kill-pane
bind L next-layout
bind H previous-layout
bind o resize-pane -Z
bind b break-pane
bind-key J command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key I command-prompt -p "send pane to:"  "join-pane -t '%%'"
# Fix escape delay
set -sg escape-time 0

# Enable cursor shape changing for neovim in tmux
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Intelligent navigation through tmux and vim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
	| grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n M-h if-shell "$is_vim" "send-keys M-h"  "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys M-j"  "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys M-k"  "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys M-l"  "select-pane -R"
bind-key -n M-\ if-shell "$is_vim" "send-keys M-\\" "select-pane -l"

set-window-option -g automatic-rename off
set-option -g allow-rename off


# Powerline theme disaster
source ~/.tmux-theme

# Set custom terminfo for italics and 256 colors
set -g default-terminal "xterm-256color"

# resize the panes
bind j resize-pane -D 10
bind k resize-pane -U 10
bind h resize-pane -L 20
bind l resize-pane -R 20

# Faster key repitition
set -g repeat-time 300
set -g escape-time 0

#window notification
set-window-option -g monitor-activity on
set-option -g bell-action any
set-option -g visual-bell off

# small splits
bind _ split-window -v -p 22 -c "#{pane_current_path}"
bind | split-window -h -p 33 -c "#{pane_current_path}"

# choose client to detach
bind-key D choose-client

# sync panes
bind C-s set-window-option synchronize-panes

# rotate panes
bind-key R rotate-window

# Move window right/left
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# renumber
bind e movew -r

# switch to previous session
bind-key T switch-client -l

# switch to previous layout
bind-key u select-layout -o

# rename window/session
bind-key , command-prompt "rename-window '%%'"
bind-key < command-prompt "rename-session '%%'"

# new named session
bind-key C command-prompt -p "Name of new session:" "new-session -s '%%' -n 'main'"

# close current session
bind-key X confirm-before -p "Kill #S (y/n)?" "run-shell 'tmux switch-client -n \\\; kill-session -t \"\$(tmux display-message -p \"#S\")\"'"

# ssh cluster
unbind a
bind-key a run "tmux split-window 'tmux resize-pane -Z | ~/.scripts/sshs -m'"

# switch to session
bind-key S run "tmux split-window 'tmux resize-pane -Z | ~/.scripts/ftsession'"

# run-shell ~/.scripts/tmux-battery/battery.tmux
 
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'Morantron/tmux-fingers'

run '~/.tmux/plugins/tpm/tpm'
