set -g status-position bottom
set -g status-justify "left"
set -g status-style "bg=#282C34"
set -g window-style "bg=#2C323D"
set -g mode-style "bg=#505868 fg=#46D9FF"

set -g status-left "#[fg=colour03]  #[fg=colour05]#S "
set -g status-left-length 100

set -g status-right "#[fg=colour03]%I:%M %p  %b %d [#{battery_status_fg}#{battery_percentage}#[fg=colour=03]] "
set -g status-right-style "bold"
set -g status-right-length 100

set -g window-status-current-style "bold fg=colour04 bg=#282C34"
set -g window-status-style "fg=colour08 bg=#282C34"
set -g window-status-format "#{?#{==:#{window_name},zsh},#{b:pane_current_path},#W}#{?window_zoomed_flag,.Z,} "
set -g window-status-current-format "#{?#{==:#{window_name},zsh},#{b:pane_current_path},#W}#{?window_zoomed_flag,.Z,} "
set -g window-status-separator ""

set -g pane-active-border-style "fg=#282C34 bg=#282C34"
set -g pane-border-style "fg=#282C34 bg=#282C34"

set -g window-active-style "bg=#282C34"
