return {
  Boolean = { fg = '#9ece6a' };
  BufferCurrent = { fg = '#e0af68', bg = '#24283b', style = 'bold' };
  BufferCurrentMod = { fg = '#7aa2f7', bg = '#24283b' };
  BufferCurrentSign = { fg = '#7aa2f7', bg = '#24283b' };
  BufferInactive = { fg = '#c0caf5', bg = '#292e42' };
  BufferInactiveMod = { fg = '#7aa2f7', bg = '#292e42' };
  BufferInactiveSign = { fg = '#7aa2f7', bg = '#292e42' };
  BufferInactiveTarge = { fg = '#c0caf5', bg = '#292e42' };
  BufferTabPageFill = { fg = '#7aa2f7', bg = '#24283b' };
  Character = { fg = '#9ece6a' };
  ColorColumn = { fg = 'none', bg = '#414868' };
  Comment = { fg = '#565f89', style = 'italic' };
  Conceal = { fg = '#737aa2', bg = 'none' };
  Conditional = { fg = '#9d7cd8' };
  Constant = { fg = '#ff9e64', style = 'italic' };
  Cursor = { fg = 'none', bg = 'none', style = 'reverse' };
  CursorColumn = { fg = 'none', bg = '#292e42' };
  CursorIm = { fg = 'none', bg = 'none', style = 'reverse' };
  CursorLine = { fg = 'none', bg = '#292e42' };
  CursorLineNr = { fg = '#737aa2', style = 'bold' };
  Define = { fg = '#9d7cd8' };
  DiffAdd = { fg = '#164846', bg = '#24283b' };
  DiffChange = { fg = '#394b70', bg = '#24283b' };
  DiffDelete = { fg = '#823c41', bg = '#24283b' };
  DiffText = { fg = '#24283b', bg = '#c0caf5' };
  Directory = { fg = '#c0caf5', bg = 'none' };
  EndOfBuffer = { fg = '#24283b', bg = 'none' };
  Error = { fg = '#f7768e' };
  ErrorMsg = { fg = '#f7768e', bg = 'none', style = 'bold' };
  Exception = { fg = '#7dcfff' };
  Float = { fg = '#9ece6a' };
  FoldColumn = { fg = '#c0caf5', bg = '#24283b' };
  Folded = { fg = '#7aa2f7', bg = '#3b4261' };
  Function = { fg = '#7aa2f7' };
  Identifier = { fg = '#bb9af7' };
  IncSearch = { fg = '#414868', bg = '#ff9e64' };
  LineNr = { fg = '#3b4261' };
  Macro = { fg = '#e0af68' };
  MatchParen = { fg = '#ff9e64', bg = 'none' };
  ModeMsg = { fg = '#c0caf5', bg = 'none', style = 'bold' };
  NonText = { fg = '#545c7e' };
  Normal = { bg = '#24283b' };
  NormalFloat = { fg = '#c0caf5', bg = '#292e42' };
  Operator = { fg = '#89ddff' };
  Pmenu = { fg = '#c0caf5', bg = '#1f2335' };
  PmenuSbar = { fg = '#9d7cd8', bg = '#292e42' };
  PmenuSel = { fg = '#292e42', bg = '#0db9d7' };
  PmenuThumb = { bg = '#3b4261' };
  PreProc = { fg = '#7dcfff' };
  Question = { fg = '#7aa2f7' };
  QuickFixLine = { fg = '#9d7cd8', style = 'bold' };
  Repeat = { fg = '#9d7cd8' };
  Search = { fg = '#24283b', bg = '#c0caf5' };
  SignColumn = { fg = 'none', bg = 'none' };
  Special = { fg = '#2ac3de' };
  SpecialChar = { fg = '#e0af68' };
  SpecialComment = { fg = '#292e42' };
  SpecialKey = { fg = '#545c7e' };
  SpellBad = { fg = '#f7768e', bg = 'none', style = 'undercurl' };
  SpellCap = { fg = '#e0af68', bg = 'none', style = 'undercurl' };
  SpellLocal = { fg = '#0db9d7', bg = 'none', style = 'undercurl' };
  SpellRare = { fg = '#89ddff', bg = 'none', style = 'undercurl' };
  Statement = { fg = '#bb9af7' };
  StatusLine = { fg = '#292e42', bg = '#3b4261', style = 'none' };
  StatusLineNc = { fg = '#292e42', bg = '#3b4261', style = 'none' };
  StorageClass = { fg = '#f7768e', style = 'italic' };
  String = { fg = '#9ece6a' };
  Structure = { fg = '#f7768e', style = 'italic' };
  TSAnnotation = { fg = '#9d7cd8' };
  TSAttribute = { fg = '#e0af68' };
  TSBoolean = { fg = '#9ece6a' };
  TSCharacter = { fg = '#9ece6a' };
  TSConstBuiltin = { fg = '#7dcfff', style = 'italic' };
  TSConstant = { fg = '#f7768e', style = 'italic' };
  TSConstructor = { fg = '#c0caf5' };
  TSField = { fg = '#73daca' };
  TSFunction = { fg = '#7aa2f7' };
  TSFunctionBuiltin = { fg = '#7aa2f7' };
  TSInclude = { fg = '#9d7cd8' };
  TSKeyword = { fg = '#9d7cd8' };
  TSKeywordFunction = { fg = '#bb9af7' };
  TSKeywordOperator = { fg = '#9d7cd8' };
  TSLabel = { fg = '#7aa2f7' };
  TSMath = { fg = '#9ece6a' };
  TSMethod = { fg = '#7aa2f7' };
  TSNamespace = { fg = '#e0af68' };
  TSNumber = { fg = '#e0af68' };
  TSParameter = { fg = '#e0af68', style = 'italic' };
  TSPunctBracket = { fg = '#a9b1d6' };
  TSPunctDelimitter = { fg = '#89ddff' };
  TSPunctSpecial = { fg = '#e0af68' };
  TSSymbol = { fg = '#e0af68' };
  TSText = { fg = '#9ece6a' };
  TSTextReference = { fg = '#1abc9c' };
  TSType = { fg = '#e0af68' };
  TSTypeBuiltin = { fg = '#bb9af7' };
  TSVariableBuiltin = { fg = '#f7768e' };
  TablineFill = { style = 'none' };
  TablineSel = { bg = '#24283b', fg = '#7aa2f7' };
  Tag = { fg = '#e0af68' };
  Terminal = { fg = '#c0caf5', bg = '#24283b' };
  Title = { fg = '#9d7cd8', style = 'bold' };
  Todo = { fg = '#e0af68', style = 'italic' };
  Type = { fg = '#2ac3de', style = 'italic' };
  Typedef = { fg = '#9d7cd8' };
  Underlined = { style = 'underline' };
  VertSplit = { fg = '#24283b' };
  Visual = { fg = 'none', bg = '#3b4261' };
  VisualNos = { fg = '#24283b', bg = '#24283b', style = 'underline' };
  WarningMsg = { fg = '#e0af68', bg = 'none', style = 'bold' };
  Whitespace = { fg = '#292e42' };
  WildMenu = { fg = '#c0caf5', bg = '#9ece6a' };
  DebugBreakpoint = { fg = '#24283b', bg = '#f7768e' };
  BufferLineSeparator = { fg = '#24283b', bg = '#292e42' };
  BufferLineSeparatorSelected = { fg = '#24283b', bg = '#292e42' };
  WhichKeyFloat = { fg = '#c0caf5', bg = '#1f2335' };
  NvimTreeNormal = { fg = '#c0caf5', bg = '#1f2335' };
}
