return {
  "catppuccin/nvim",
  name = "catppuccin",
  enabled = false,
  lazy = false,
  priority = 1000,
  config = function()
    vim.opt.background = "dark"

    local carbon = {
      black = "#000000",
      blue10 = "#edf5ff",
      blue100 = "#001141",
      blue20 = "#d0e2ff",
      blue30 = "#a6c8ff",
      blue40 = "#78a9ff",
      blue50 = "#4589ff",
      blue60 = "#0f62fe",
      blue70 = "#0043ce",
      blue80 = "#002d9c",
      blue90 = "#001d6c",
      cyan10 = "#e5f6ff",
      cyan100 = "#061727",
      cyan20 = "#bae6ff",
      cyan30 = "#82cfff",
      cyan40 = "#33b1ff",
      cyan50 = "#1192e8",
      cyan60 = "#0072c3",
      cyan70 = "#00539a",
      cyan80 = "#003a6d",
      cyan90 = "#012749",
      gray10 = "#f4f4f4",
      gray100 = "#161616",
      gray20 = "#e0e0e0",
      gray30 = "#c6c6c6",
      gray40 = "#a8a8a8",
      gray50 = "#8d8d8d",
      gray60 = "#6f6f6f",
      gray70 = "#525252",
      gray80 = "#393939",
      gray90 = "#262626",
      gray10Hover = "#e8e8e8",
      gray20Hover = "#d1d1d1",
      gray30Hover = "#b5b5b5",
      gray40Hover = "#999999",
      gray50Hover = "#7a7a7a",
      gray60Hover = "#5e5e5e",
      gray70Hover = "#636363",
      gray80Hover = "#474747",
      gray90Hover = "#333333",
      gray100Hover = "#292929",
      green10 = "#defbe6",
      green100 = "#071908",
      green20 = "#a7f0ba",
      green30 = "#6fdc8c",
      green40 = "#42be65",
      green50 = "#24a148",
      green60 = "#198038",
      green70 = "#0e6027",
      green80 = "#044317",
      green90 = "#022d0d",
      magenta10 = "#fff0f7",
      magenta100 = "#2a0a18",
      magenta20 = "#ffd6e8",
      magenta30 = "#ffafd2",
      magenta40 = "#ff7eb6",
      magenta50 = "#ee5396",
      magenta60 = "#d02670",
      magenta70 = "#9f1853",
      magenta80 = "#740937",
      magenta90 = "#510224",
      orange10 = "#fff2e8",
      orange100 = "#231000",
      orange20 = "#ffd9be",
      orange30 = "#ffb784",
      orange40 = "#ff832b",
      orange50 = "#eb6200",
      orange60 = "#ba4e00",
      orange70 = "#8a3800",
      orange80 = "#5e2900",
      orange90 = "#3e1a00",
      purple10 = "#f6f2ff",
      purple100 = "#1c0f30",
      purple20 = "#e8daff",
      purple30 = "#d4bbff",
      purple40 = "#be95ff",
      purple50 = "#a56eff",
      purple60 = "#8a3ffc",
      purple70 = "#6929c4",
      purple80 = "#491d8b",
      purple90 = "#31135e",
      red10 = "#fff1f1",
      red100 = "#2d0709",
      red20 = "#ffd7d9",
      red30 = "#ffb3b8",
      red40 = "#ff8389",
      red50 = "#fa4d56",
      red60 = "#da1e28",
      red70 = "#a2191f",
      red80 = "#750e13",
      red90 = "#520408",
      teal10 = "#d9fbfb",
      teal100 = "#081a1c",
      teal20 = "#9ef0f0",
      teal30 = "#3ddbd9",
      teal40 = "#08bdba",
      teal50 = "#009d9a",
      teal60 = "#007d79",
      teal70 = "#005d5d",
      teal80 = "#004144",
      teal90 = "#022b30",
      white = "#ffffff",
      yellow10 = "#fcf4d6",
      yellow100 = "#1c1500",
      yellow20 = "#fddc69",
      yellow30 = "#f1c21b",
      yellow40 = "#d2a106",
      yellow50 = "#b28600",
      yellow60 = "#8e6a00",
      yellow70 = "#684e00",
      yellow80 = "#483700",
      yellow90 = "#302400",
    }

    require("catppuccin").setup({
      integrations = {
        cmp = true,
        gitsigns = true,
        which_key = true,
        flash = true,
        dashboard = false,
        lsp_trouble = true,
        telescope = {
          enabled = true,
          style = "nvchad",
        },
        nvimtree = true,
        treesitter = true,
        notify = true,
        noice = true,
        neotest = true,
        mason = true,
        mini = {
          enabled = true,
        },
      },
      term_colors = true,
      background = {
        dark = "mocha",
        light = "latte",
      },
      highlight_overrides = {
        all = function(colors)
          return {
            -- Comment = { fg = colors.peach, style = { "italic" } },
            -- Boolean = { fg = colors.sky },
            -- Conditional = { fg = colors.flamingo },
            -- CursorLine = { bg = colors.mantle },
            -- Function = { fg = colors.sky, style = { "bold" } },
            -- LineNr = { fg = colors.overlay1 },
            -- MiniIndentscopeSymbol = { fg = colors.surface2 },
            -- Operator = { fg = colors.overlay2 },
            -- PreProc = { fg = colors.blue },
            -- String = { fg = colors.sky },
            -- TSConstructor = { fg = colors.text },
            -- TSFuncBuiltin = { fg = colors.flamingo },
            -- TSFunction = { fg = colors.flamingo },
            -- TSParameter = { fg = colors.text },
            -- TSVariableBuiltin = { fg = colors.flamingo },
            -- TelescopeBorder = { bg = colors.base, fg = colors.base },
            -- TelescopeMatching = { fg = colors.sapphire },
            -- TelescopeNormal = { bg = colors.base },
            -- TelescopeSelection = { bg = colors.surface2, fg = colors.text },
            -- TodoBgTODO = { fg = colors.base, bg = colors.green },
            -- TodoFgTODO = { fg = colors.green },
            -- Type = { fg = colors.blue },
            -- Variable = { fg = colors.text },
            -- ["@constructor.lua"] = { fg = colors.overlay2 },
            -- ["@constant.ruby"] = { fg = colors.blue },
            -- ["@function.builtin"] = { fg = colors.flamingo, style = { "bold" } },
            -- ["@function.call.ruby"] = { fg = colors.teal },
            -- ["@lsp.type.method.ruby"] = { fg = colors.sky, style = { "bold" } },
            -- ["@function.ruby"] = { fg = colors.sky, style = { "bold" } },
            -- ["@keyword.function.ruby"] = { fg = colors.teal },
            -- ["@keyword.function.lua"] = { fg = colors.mauve },
            -- ["@lsp.type.class.ruby"] = { fg = colors.blue, style = { "bold" } },
            -- ["@module"] = { fg = colors.peach, style = { "bold", "italic" } },
            -- ["@parameter"] = { fg = colors.flamingo },
            -- ["@property"] = { fg = colors.text },
            -- ["@string.special.symbol.ruby"] = { fg = colors.lavender },
            -- ["@variable"] = { fg = colors.text },
            -- ["@variable.parameter"] = { fg = colors.flamingo },
          }
        end,
      },
      -- color_overrides = {
      --   mocha = {
      --     rosewater = carbon.red30,
      --     flamingo = carbon.magenta40,
      --     red = carbon.red50,
      --     maroon = carbon.red30,
      --     pink = carbon.magenta30,
      --     mauve = carbon.purple50,
      --     peach = carbon.orange40,
      --     yellow = carbon.yellow30,
      --     green = carbon.green40,
      --     teal = carbon.teal40,
      --     sky = carbon.cyan30,
      --     sapphire = carbon.cyan50,
      --     blue = carbon.blue40,
      --     lavender = carbon.purple30,
      --     text = carbon.gray10,
      --     subtext1 = carbon.gray30,
      --     subtext0 = carbon.gray40,
      --     overlay2 = carbon.gray50,
      --     overlay1 = carbon.gray60,
      --     overlay0 = carbon.gray70,
      --     surface2 = carbon.gray80,
      --     surface1 = carbon.gray100Hover,
      --     surface0 = carbon.gray100,
      --     base = carbon.gray100,
      --     mantle = carbon.gray100Hover,
      --     crust = carbon.gray90,
      --   },
      -- },
    })

    vim.cmd.colorscheme("catppuccin")
  end,
}
