return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "RRethy/nvim-treesitter-endwise",
  },
  build = ":TSUpdate",
  cond = true,
  event = "BufReadPre",
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "fish",
        "dockerfile",
        "eex",
        "erlang",
        "elixir",
        "go",
        "haskell",
        "heex",
        "html",
        "hyprlang",
        "java",
        "javascript",
        "julia",
        "lua",
        "make",
        "markdown",
        "php",
        "python",
        "ruby",
        "rust",
        "scss",
        "surface",
        "svelte",
        "typescript",
        "vim",
        "yaml",
      },
      sync_install = false,
      highlight = { enable = true },
      endwise = { enable = true },
    })
  end,
}
