- hosts: all
  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - asdf
        - bat
        - coreutils
        - curl
        - docker
        - fasd
        - fd
        - figlet
        - findutils
        - fortune
        - fzf
        - gawk
        - gawk
        - gcc
        - gnu-sed
        - gnu-tar
        - htop
        - httpie
        - luarocks
        - markdown
        - neovim
        - nnn
        - nvm
        - ripgrep
        - ruby
        - speedtest-cli
        - stow
        - tmux
        - universal-ctags
        - zinit
