[metadata]
name = "mise-tasks"
description = "Browse and run mise tasks"
requirements = ["mise"]

[source]
command = ["mise tasks ls --no-header | awk '{print $1}'"]

[preview]
command = "mise tasks info {}"

[keybindings]
ctrl-x = "actions:execute-task"
ctrl-w = "actions:watch-task"

[actions.execute-task]
description = "Execute the selected mise task"
command = "mise run {}"
mode = "execute"

[actions.watch-task]
description = "Run the selected mise task in watch mode"
command = "mise watch {}"
mode = "execute"
